Ext.define('Project1.project1.web.com.view.newbc.newdomain.CompleteUi', {
     "xtype": "completeUiView",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "candidateName",
          "margin": 5,
          "bindable": "candidateName",
          "name": "candidateName",
          "text": "candidateName",
          "fieldName": "candidateName",
          "displayName": "candidateName",
          "widget": "textfield",
          "min": "1",
          "max": "256",
          "isField": true,
          "itemId": "textfield_ext_18970"
     }, {
          "xtype": "combo",
          "name": "interviewere",
          "margin": 5,
          "bindable": "interviewere",
          "typeAhead": true,
          "queryMode": "local",
          "minChars": 1,
          "fieldLabel": "interviewere",
          "displayField": "interviewerr",
          "valueField": "interviewrId",
          "text": "interviewere",
          "fieldName": "interviewere",
          "displayName": "interviewere",
          "widget": "combo",
          "min": "1",
          "max": "256",
          "isField": true,
          "itemId": "combo_ext_18979",
          "store": {
               "model": "Project1.project1.shared.com.model.newbc.newdomain.InterviewerModel",
               "autoLoad": true,
               "autoSync": true,
               "sorters": [{
                    "property": "interviewerr",
                    "direction": "ASC"
               }],
               "proxy": {
                    "type": "ajax",
                    "url": "secure/Interviewer/findAll",
                    "serviceId": "315D13B2-3950-4F62-887B-8FD7253F2888",
                    "serviceType": 1,
                    "serviceOperationId": "45C8F07A-4FCC-4066-B19A-D1211E2BCC34",
                    "operationName": "findAll",
                    "operationDisplayName": "findAll",
                    "actionMethods": {
                         "read": "GET"
                    },
                    "headers": {
                         "Content-Type": "application/json"
                    },
                    "extraParams": {},
                    "reader": {
                         "type": "json",
                         "rootProperty": "response.data"
                    }
               }
          }
     }, {
          "xtype": "textfield",
          "fieldLabel": "emailid",
          "margin": 5,
          "bindable": "emailid",
          "name": "emailid",
          "text": "emailid",
          "fieldName": "emailid",
          "displayName": "emailid",
          "widget": "textfield",
          "min": "1",
          "max": "256",
          "isField": true,
          "itemId": "textfield_ext_19003"
     }, {
          "xtype": "datefields",
          "fieldLabel": "datee",
          "name": "datee",
          "bindable": "datee",
          "margin": 5,
          "text": "datee",
          "fieldName": "datee",
          "displayName": "datee",
          "widget": "datefield",
          "isField": true,
          "itemId": "datefield_ext_19018",
          "submitFormat": "d-m-Y"
     }, {
          "xtype": "textareafield",
          "fieldLabel": "note",
          "name": "note",
          "margin": 5,
          "bindable": "note",
          "text": "note",
          "fieldName": "note",
          "displayName": "note",
          "widget": "textareafield",
          "min": "1",
          "max": "256",
          "isField": true,
          "itemId": "textareafield_ext_19054"
     }, {
          "xtype": "customradiogroup",
          "name": "recommendHire",
          "bindable": "recommendHire",
          "fieldLabel": "recommendHire",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "itemId": "radiogroup_ext_19077",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "recommendHire",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "recommendHire",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "star",
          "bindable": "star",
          "fieldLabel": "star",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "itemId": "radiogroup_ext_19098",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "star",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "star",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "skillFit",
          "bindable": "skillFit",
          "fieldLabel": "skillFit",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "itemId": "radiogroup_ext_19122",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "skillFit",
               "checked": false,
               "id": "extModel64-37"
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "skillFit",
               "checked": false,
               "id": "extModel64-38"
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "cultureFit",
          "bindable": "cultureFit",
          "fieldLabel": "cultureFit",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "itemId": "radiogroup_ext_19149",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "cultureFit",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "cultureFit",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "growthPotential",
          "bindable": "growthPotential",
          "fieldLabel": "growthPotential",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "itemId": "radiogroup_ext_19179",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "growthPotential",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "growthPotential",
               "checked": false
          }]
     }, {
          "xtype": "button",
          "name": "savr",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_21881",
          "listeners": {
               "click": "onSavrClick"
          }
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "itemId": "form_ext_18959",
     "dockedItems": [],
     "requires": ["Project1.project1.shared.com.model.newbc.newdomain.InterviewerModel", "Project1.project1.web.com.controller.newbc.newdomain.CompleteUiController", "Project1.project1.shared.com.viewmodel.newbc.newdomain.CompleteUiViewModel", "Project1.project1.shared.com.model.newbc.newdomain.CompleteUiModel", "Project1.view.fw.component.DateFields", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup"],
     "extend": "Ext.form.Panel",
     "viewModel": "CompleteUiViewModel",
     "controller": "CompleteUiController"
});