Ext.define('Project1.project1.web.com.view.newbc.newdomain.TestVd', {
     "xtype": "testVdView",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "candidateName",
          "margin": 5,
          "bindable": "candidateName",
          "name": "candidateName",
          "text": "candidateName",
          "fieldName": "candidateName",
          "displayName": "candidateName",
          "widget": "textfield",
          "min": "1",
          "max": "256",
          "isField": true,
          "allowModify": true,
          "itemId": "textfield_ext_14264"
     }, {
          "xtype": "combo",
          "name": "interviewere",
          "margin": 5,
          "bindable": "interviewere",
          "typeAhead": true,
          "queryMode": "local",
          "minChars": 1,
          "fieldLabel": "interviewere",
          "displayField": "interviewerr",
          "valueField": "interviewrId",
          "text": "interviewere",
          "fieldName": "interviewere",
          "displayName": "interviewere",
          "widget": "combo",
          "min": "1",
          "max": "256",
          "isField": true,
          "allowModify": true,
          "itemId": "combo_ext_14273",
          "store": {
               "model": "Project1.project1.shared.com.model.newbc.newdomain.InterviewerModel",
               "autoLoad": true,
               "autoSync": true,
               "sorters": [{
                    "property": "interviewerr",
                    "direction": "ASC"
               }],
               "proxy": {
                    "type": "ajax",
                    "url": "secure/Interviewer/findAll",
                    "serviceId": "315D13B2-3950-4F62-887B-8FD7253F2888",
                    "serviceType": 1,
                    "serviceOperationId": "45C8F07A-4FCC-4066-B19A-D1211E2BCC34",
                    "operationName": "findAll",
                    "operationDisplayName": "findAll",
                    "actionMethods": {
                         "read": "GET"
                    },
                    "headers": {
                         "Content-Type": "application/json"
                    },
                    "extraParams": {},
                    "reader": {
                         "type": "json",
                         "rootProperty": "response.data"
                    }
               }
          }
     }, {
          "xtype": "textfield",
          "fieldLabel": "emailid",
          "margin": 5,
          "bindable": "emailid",
          "name": "emailid",
          "text": "emailid",
          "fieldName": "emailid",
          "displayName": "emailid",
          "widget": "textfield",
          "min": "1",
          "max": "256",
          "isField": true,
          "allowModify": true,
          "itemId": "textfield_ext_14284"
     }, {
          "xtype": "datefields",
          "fieldLabel": "datee",
          "name": "datee",
          "bindable": "datee",
          "margin": 5,
          "text": "datee",
          "fieldName": "datee",
          "displayName": "datee",
          "widget": "datefield",
          "isField": true,
          "allowModify": true,
          "itemId": "datefield_ext_14297",
          "submitFormat": "d-m-Y"
     }, {
          "xtype": "textareafield",
          "fieldLabel": "note",
          "name": "note",
          "margin": 5,
          "bindable": "note",
          "text": "note",
          "fieldName": "note",
          "displayName": "note",
          "widget": "textareafield",
          "min": "1",
          "max": "256",
          "isField": true,
          "allowModify": true,
          "itemId": "textareafield_ext_14313"
     }, {
          "xtype": "customradiogroup",
          "name": "skillFit",
          "bindable": "skillFit",
          "fieldLabel": "skillFit",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "allowModify": true,
          "itemId": "radiogroup_ext_14390",
          "items": [{
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "skillFit",
               "checked": false
          }, {
               "boxLabel": "no",
               "inputValue": "0",
               "name": "skillFit",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "cultureFit",
          "bindable": "cultureFit",
          "fieldLabel": "cultureFit",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "allowModify": true,
          "itemId": "radiogroup_ext_14411",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "cultureFit",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "cultureFit",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "grothPotential",
          "bindable": "grothPotential",
          "fieldLabel": "grothPotential",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "allowModify": true,
          "itemId": "radiogroup_ext_14435",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "grothPotential",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "grothPotential",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "star",
          "bindable": "star",
          "fieldLabel": "star",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "allowModify": true,
          "itemId": "radiogroup_ext_14462",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "star",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "star",
               "checked": false
          }]
     }, {
          "xtype": "customradiogroup",
          "name": "RecommendHire",
          "bindable": "RecommendHire",
          "fieldLabel": "RecommendHire",
          "columns": 2,
          "vertical": true,
          "margin": 5,
          "isDynamic": false,
          "allowModify": true,
          "itemId": "radiogroup_ext_14492",
          "items": [{
               "boxLabel": "no",
               "inputValue": "0",
               "name": "RecommendHire",
               "checked": false
          }, {
               "boxLabel": "yes",
               "inputValue": "1",
               "name": "RecommendHire",
               "checked": false
          }]
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "dockedItems": [],
     "allowModify": true,
     "itemId": "form_ext_14250",
     "requires": ["Project1.project1.shared.com.model.newbc.newdomain.InterviewerModel", "Project1.project1.web.com.controller.newbc.newdomain.TestVdController", "Project1.project1.shared.com.viewmodel.newbc.newdomain.TestVdViewModel", "Project1.project1.shared.com.model.newbc.newdomain.TestVdModel", "Project1.view.fw.component.DateFields", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup", "Project1.view.fw.component.CustomRadioGroup"],
     "extend": "Ext.form.Panel",
     "viewModel": "TestVdViewModel",
     "controller": "TestVdController"
});