Ext.define('Project1.project1.shared.com.model.newbc.newdomain.CandidateModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "candidateId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "candidateName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "interviewere",
          "reference": "Interviewer",
          "defaultValue": ""
     }, {
          "name": "recommendHire",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "emailid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "datee",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "skillFit",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cultureFit",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "growthPotential",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "star",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "note",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});