DROP TABLE IF EXISTS `ast_FGPT_TP`;

CREATE TABLE `ast_FGPT_TP` ( `testFGid` VARCHAR(256) NOT NULL, `ptPk` VARCHAR(256) NOT NULL, `ptName` VARCHAR(256) NOT NULL, `ptDate` DATE NOT NULL, `ptDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`ptPk`));

