Ext.define('Project1.project1.shared.com.model.newbc.newdomain.CompleteUiModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "candidateName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "interviewere",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "emailid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "datee",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "note",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "recommendHire",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "star",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "skillFit",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "cultureFit",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "growthPotential",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "savr",
          "type": "auto",
          "defaultValue": ""
     }]
});