Ext.define('Project1.project1.shared.com.model.newbc.newdomain.ProductModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "productId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "pName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "pDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "pdatetime",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "image",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});